### ISSUE TITLE
Directory separators at pattern start or middle are not handled correctly

### ISSUE THREAD

**Issue by eemeli** [pacha/gitignore-match#5]
In brief, this happens:
```python
from py_walk import get_parser_from_text
parser = get_parser_from_text('/two', base_dir='/one')
parser.match('/one/two')  # True, as expected
parser.match('/one/three/two')  # True, but should be False
```

According to the [gitignore docs](https://git-scm.com/docs/gitignore#_pattern_format):

> If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular `.gitignore` file itself. Otherwise the pattern may also match at any level below the `.gitignore` level.
>
> If there is a separator at the end of the pattern then the pattern will only match directories, otherwise the pattern can match both files and directories.
>
> For example, a pattern `doc/frotz/` matches `doc/frotz` directory, but not `a/doc/frotz` directory; however `frotz/` matches `frotz` and `a/frotz` that is a directory (all paths are relative from the `.gitignore` file).

**Comment by pacha** [comment]
Hi @eemeli!
I'm really some kind of special... After hundreds of test cases, I missed that really basic one. It is fixed now in version `0.3.2`. Thanks a lot for noticing and reporting! (and providing such a clear example :)

ps. Also, sorry for the super delayed response!
